baseURL = 'http://sophiebosio.github.io/'
languageCode = 'en-us'
title = 'Sophie Bosio'
theme = 'PaperMod'
paginate = 5

[params]
  defaultTheme = "auto"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false
  # Format of dates
  dateFormat = "02 January 2006"
  
[params.homeInfoParams]
	title = "Hi, I'm Sophie"
    content = "I"

   	# socialIcons: # optional
    #     - name: "<platform>"
    #       url: "<link>"
    #     - name: "<platform 2>"
    #       url: "<link2>"


[languages]
  [languages.en]
    title = "Sophie Bosio"
    subtitle = "Blog"
    keywords = ""
    copyright = "Copyright (c) Sophie Bosio 2023"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    # leave empty to disable, enter display text to enable
    lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Sophie Bosio"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "education"
        name = "Education"
        url = "/education"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "https://github.com/SophieBosio"

# Syntax highlighting!
[markup.highlight]
	codeFences = true
	guessSyntax = true
	hl_Lines = ""
	lineNoStart = 1
	lineNos = false
	lineNumbersInTable = false
	tabWidth = 4
	noClasses = false

[markup.goldmark.renderer]
  unsafe = true
